/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bankaccount.view;

import bankaccount.common.Utils;
import bankaccount.controller.AccountController;
import bankaccount.model.Account;
import bankaccount.model.CreditAccount;
import bankaccount.model.Customer;
import bankaccount.model.NormalSpendAccount;
import bankaccount.model.VipSpendAccount;
import java.math.BigDecimal;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author ADMIN
 */
public class EditAccountForm extends javax.swing.JFrame {

    private AccountForm accountForm;
    private AccountController accountController;
    private NormalSpendAccount normalSpendAccount;
    private VipSpendAccount vipSpendAccount;
    private CreditAccount creditAccount;
    private String oldAccountNo;

    /**
     * Creates new form EditAccountForm
     */
    public EditAccountForm() {
        initComponents();
        accountController = new AccountController();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCreditLimit = new javax.swing.JTextField();
        txtAccountNo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtAccountName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCashLimit = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jDateOpenAccount = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Sửa thông tin tài khoản");

        jLabel2.setText("Số TK");

        jLabel3.setText("Chủ tài khoản");

        jLabel5.setText("Hạn mức chi tiêu");

        jLabel4.setText("Ngày mở");

        jLabel6.setText("Hạn mức tín dụng");

        jButton1.setText("Sửa");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Quay lại");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(125, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(97, 97, 97))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtCreditLimit, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtCashLimit, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtAccountNo, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                                .addComponent(txtAccountName))
                            .addComponent(jDateOpenAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 264, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(67, 67, 67)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtAccountNo, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtAccountName, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jDateOpenAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtCashLimit, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtCreditLimit, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(109, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        List<Account> accounts = accountController.getAllAccounts();
        if (accounts == null) {
            JOptionPane.showMessageDialog(this, "Có lỗi xảy ra...");
            return;
        }
        this.accountForm.setAccountList(accounts);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String accountNo = txtAccountNo.getText();
        String accountName = txtAccountName.getText();
        Date openDate = jDateOpenAccount.getDate();
        String cashLimit = txtCashLimit.getText();
        String creditLimit = txtCreditLimit.getText();
        boolean result = false;
        if (!cashLimit.isEmpty()) {
            if (normalSpendAccount != null) {
                normalSpendAccount.setAccountNo(accountNo);
                normalSpendAccount.setAccountName(accountName);
                normalSpendAccount.setOpenDate(openDate);
                normalSpendAccount.setCashLimit(new BigDecimal(cashLimit));
                result = accountController.update(normalSpendAccount, oldAccountNo);
            } else if (vipSpendAccount != null) {
                vipSpendAccount.setAccountNo(accountNo);
                vipSpendAccount.setAccountName(accountName);
                vipSpendAccount.setOpenDate(openDate);
                vipSpendAccount.setCashLimit(new BigDecimal(cashLimit));
                result = accountController.update(vipSpendAccount, oldAccountNo);
            }
        } else if (!creditLimit.isEmpty()) {
            if (creditAccount != null) {
                creditAccount.setAccountNo(accountNo);
                creditAccount.setAccountName(accountName);
                creditAccount.setOpenDate(openDate);
                creditAccount.setCreditLimit(new BigDecimal(creditLimit));
                result = accountController.update(creditAccount, oldAccountNo);
            }
        }
        if (!result) {
            JOptionPane.showMessageDialog(this, "Update Account không thành công");
            return;
        }
        JOptionPane.showMessageDialog(this, "Update Account thành công");
        List<Account> accounts = accountController.getAllAccounts();
        if (accounts == null) {
            JOptionPane.showMessageDialog(this, "Có lỗi xảy ra...");
            return;
        }
        this.accountForm.setAccountList(accounts);
        this.setVisible(false);
        this.accountForm.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditAccountForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditAccountForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditAccountForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditAccountForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditAccountForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private com.toedter.calendar.JDateChooser jDateOpenAccount;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtAccountName;
    private javax.swing.JTextField txtAccountNo;
    private javax.swing.JTextField txtCashLimit;
    private javax.swing.JTextField txtCreditLimit;
    // End of variables declaration//GEN-END:variables

    void setData(Account account) {
        this.oldAccountNo = account.getAccountNo();
        txtAccountNo.setText(account.getAccountNo());
        txtAccountName.setText(account.getAccountName());
        jDateOpenAccount.setDate(account.getOpenDate());
        String cashLimit = "";
        String creditLimit = "";
        if (account instanceof NormalSpendAccount) {
            NormalSpendAccount normalSpendAccount = (NormalSpendAccount) account;
            this.normalSpendAccount = normalSpendAccount;
            cashLimit = Utils.customCurrency("###,###.##", String.valueOf(normalSpendAccount.getCashLimit()));
            txtCreditLimit.setEnabled(false);
            txtCashLimit.setEditable(true);
        } else if (account instanceof VipSpendAccount) {
            VipSpendAccount vipSpendAccount = (VipSpendAccount) account;
            this.vipSpendAccount = vipSpendAccount;
            cashLimit = Utils.customCurrency("###,###.##", String.valueOf(vipSpendAccount.getCashLimit()));
            txtCreditLimit.setEnabled(false);
            txtCashLimit.setEditable(true);
        } else {
            CreditAccount creditAccount = (CreditAccount) account;
            this.creditAccount = creditAccount;
            creditLimit = Utils.customCurrency("###,###.##", String.valueOf(creditAccount.getCreditLimit()));
            txtCashLimit.setEnabled(false);
            txtCreditLimit.setEditable(true);
        }
        txtCashLimit.setText(cashLimit);
        txtCreditLimit.setText(creditLimit);
    }

    void setForm(AccountForm accountForm) {
        this.accountForm = accountForm;
    }
}
